FROM python:3.9-slim

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install pandas pytest hypothesis 

RUN mkdir /app
WORKDIR /app
ADD app.py /app

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

ENV PYTHONUNBUFFERED=1

CMD ["/bin/bash"]
